### ISSUE TITLE
QGIS 2.* is obsolete

### ISSUE THREAD

**Issue by pcav** [Ariel505/aChor#9]
and officially discontinued. We encourage you to upgrade to 3.4.
Cheers.

**Comment by Ariel505** [comment]
Great! Thanks for notice.

**Comment by pcav** [comment]
Better leave the ticket open, as the problem has not been solved yet.
Thanks.

**Comment by Ariel505** [comment]
we have separate versions for QGIS 2 and 3 so where is the problem?

**Comment by pcav** [comment]
Sorry I didn't notice this. It would have been preferable to have just one repository for both version, to avoid duplication.
Cheers.
